
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "webstack-go-mysql:3306"
    name = "webstack-go"
    pass = "123456"
    user = "root"

  [mysql.write]
    addr = "webstack-go-mysql:3306"
    name = "webstack-go"
    pass = "123456"
    user = "root"

[redis]
  addr = "webstack-go-redis:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = "123456"
  poolsize = 10
